In [39]:
import numpy as np

In [37]:

sequence = "MASQNRDPAATSVAAARKGAEPSGGAARGPVGKRLQQELMTLMMSGDKGISAFPESDNLFKWVGTIHGAAGTVYEDLRYKLSLEFPSGYPYNAPTVKFLTPCYHPNVDTQGNICLDILKEKWSALYDVRTILLSIQSLLGEPNIDSPLNTHAAELWKNPTAFKKYLQETYSKQVTSQEP"
chou_fasman_table = {
    'A': {'P_a': 1.42, 'P_b': 0.83, 'P_turn': 0.66, 'f_i': 0.06,  'f_i1': 0.076, 'f_i2': 0.035, 'f_i3': 0.058},
    'R': {'P_a': 0.98, 'P_b': 0.93, 'P_turn': 0.95, 'f_i': 0.070, 'f_i1': 0.106, 'f_i2': 0.099, 'f_i3': 0.085},
    'D': {'P_a': 1.01, 'P_b': 0.54, 'P_turn': 1.46, 'f_i': 0.147, 'f_i1': 0.110, 'f_i2': 0.179, 'f_i3': 0.081},
    'N': {'P_a': 0.67, 'P_b': 0.89, 'P_turn': 1.56, 'f_i': 0.161, 'f_i1': 0.083, 'f_i2': 0.191, 'f_i3': 0.091},
    'C': {'P_a': 0.70, 'P_b': 1.19, 'P_turn': 1.19, 'f_i': 0.149, 'f_i1': 0.050, 'f_i2': 0.117, 'f_i3': 0.128},
    'E': {'P_a': 1.39, 'P_b': 1.17, 'P_turn': 0.74, 'f_i': 0.056, 'f_i1': 0.060, 'f_i2': 0.077, 'f_i3': 0.064},
    'Q': {'P_a': 1.11, 'P_b': 1.10, 'P_turn': 0.98, 'f_i': 0.074, 'f_i1': 0.098, 'f_i2': 0.037, 'f_i3': 0.098},
    'G': {'P_a': 0.57, 'P_b': 0.75, 'P_turn': 1.56, 'f_i': 0.102, 'f_i1': 0.085, 'f_i2': 0.190, 'f_i3': 0.152},
    'H': {'P_a': 1.00, 'P_b': 0.87, 'P_turn': 0.95, 'f_i': 0.140, 'f_i1': 0.047, 'f_i2': 0.093, 'f_i3': 0.054},
    'I': {'P_a': 1.08, 'P_b': 1.60, 'P_turn': 0.47, 'f_i': 0.043, 'f_i1': 0.034, 'f_i2': 0.013, 'f_i3': 0.056},
    'L': {'P_a': 1.41, 'P_b': 1.30, 'P_turn': 0.59, 'f_i': 0.061, 'f_i1': 0.025, 'f_i2': 0.036, 'f_i3': 0.070},
    'K': {'P_a': 1.14, 'P_b': 0.74, 'P_turn': 1.01, 'f_i': 0.055, 'f_i1': 0.115, 'f_i2': 0.072, 'f_i3': 0.095},
    'M': {'P_a': 1.45, 'P_b': 1.05, 'P_turn': 0.60, 'f_i': 0.068, 'f_i1': 0.082, 'f_i2': 0.014, 'f_i3': 0.055},
    'F': {'P_a': 1.13, 'P_b': 1.38, 'P_turn': 0.60, 'f_i': 0.059, 'f_i1': 0.041, 'f_i2': 0.065, 'f_i3': 0.065},
    'P': {'P_a': 0.57, 'P_b': 0.55, 'P_turn': 1.52, 'f_i': 0.102, 'f_i1': 0.301, 'f_i2': 0.034, 'f_i3': 0.068},
    'S': {'P_a': 0.77, 'P_b': 0.75, 'P_turn': 1.43, 'f_i': 0.120, 'f_i1': 0.139, 'f_i2': 0.125, 'f_i3': 0.106},
    'T': {'P_a': 0.83, 'P_b': 1.19, 'P_turn': 0.96, 'f_i': 0.086, 'f_i1': 0.108, 'f_i2': 0.065, 'f_i3': 0.079},
    'W': {'P_a': 1.08, 'P_b': 1.37, 'P_turn': 0.96, 'f_i': 0.077, 'f_i1': 0.013, 'f_i2': 0.064, 'f_i3': 0.167},
    'Y': {'P_a': 0.69, 'P_b': 1.47, 'P_turn': 1.14, 'f_i': 0.082, 'f_i1': 0.065, 'f_i2': 0.114, 'f_i3': 0.125},
    'V': {'P_a': 1.06, 'P_b': 1.70, 'P_turn': 0.50, 'f_i': 0.062, 'f_i1': 0.048, 'f_i2': 0.028, 'f_i3': 0.053}
}
ground_truth = [
    ("Unknown",1,29),
    ("Helix", 30, 45),
    ("Unknown", 46, 49),
    ("Beta strand", 50, 54),
    ("Unknown", 55, 60),
    ("Beta strand", 61, 68),
    ("Unknown", 69, 77),
    ("Beta strand", 78, 84),
    ("Unknown", 85, 86),
    ("Turn", 87, 91),
    ("Unknown", 92, 94),
    ("Beta strand", 95, 100),
    ("Unknown",101,110),
    ("Beta strand", 111, 113),
    ("Unknown", 114, 115),
    ("Helix", 116, 118),
    ("Turn", 119, 121),
    ("Unknown",122,127),
    ("Helix", 128, 140),
    ("Unknown", 141, 149),
    ("Helix", 150, 155),
    ("Unknown", 156, 158),
    ("Helix", 159, 172),
    ("Unknown", 173, 179),
]


WINDOW_SIZE = 6 
Helix_THRESHOLD = 1 
BETA_THRESHOLD = 1 
TURN_THRESHOLD = 1 
BEND_THRESHOLD = 0.000075 
MIN_LENGTH = 5 


def get_Pa(residue):
    
    return chou_fasman_table[residue]['P_a']

def get_Pb(residue):
    
    return chou_fasman_table[residue]['P_b']

def get_Pturn(residue):
    
    return chou_fasman_table[residue]['P_turn']

def get_Pbend(i, i1, i2, i3):
    
    return chou_fasman_table[i]['f_i'] * chou_fasman_table[i1]['f_i1'] * chou_fasman_table[i2]['f_i2'] * chou_fasman_table[i3]['f_i3']

def predict_Helix_beta(sequence):
    
    regions = []
    
    for i in range(len(sequence) - WINDOW_SIZE + 1):
        
        segment = sequence[i:i+WINDOW_SIZE]
        
        sum_Pa = sum(get_Pa(residue) for residue in segment)
        sum_Pb = sum(get_Pb(residue) for residue in segment)
        
        if all(get_Pa(residue) > Helix_THRESHOLD for residue in segment):
            regions.append(('Helix', i+1, i+WINDOW_SIZE))
        elif all(get_Pb(residue) > BETA_THRESHOLD for residue in segment):
            regions.append(('Beta strand', i+1, i+WINDOW_SIZE))
   
    extended_regions = []
    for region in regions:
        structure, start, end = region
        while start > 1 and get_Pa(sequence[start-2]) > Helix_THRESHOLD and structure == 'Helix':
            start -= 1
        while start > 1 and get_Pb(sequence[start-2]) > BETA_THRESHOLD and structure == 'Beta strand':
            start -= 1
        while end < len(sequence) and get_Pa(sequence[end]) > Helix_THRESHOLD and structure == 'Helix':
            end += 1
        while end < len(sequence) and get_Pb(sequence[end]) > BETA_THRESHOLD and structure == 'Beta strand':
            end += 1
        extended_regions.append((structure, start, end))
    resolved_regions = []
    i = 0
    while i < len(extended_regions):
        region = extended_regions[i]
        if i < len(extended_regions) - 1 and region[2] >= extended_regions[i+1][1]:
            next_region = extended_regions[i+1]
            overlap_start = next_region[1]
            overlap_end = min(region[2], next_region[2])
            overlap_segment = sequence[overlap_start-1:overlap_end]
            sum_Pa = sum(get_Pa(residue) for residue in overlap_segment)
            sum_Pb = sum(get_Pb(residue) for residue in overlap_segment)
            if sum_Pa > sum_Pb:
                overlap_structure = 'Helix'
            else:
                overlap_structure = 'Beta strand'
            if overlap_structure == region[0]:
                region = (region[0], region[1], overlap_end)
                next_region = (next_region[0], overlap_end + 1, next_region[2])
            else:
                region = (region[0], region[1], overlap_start - 1)
                next_region = (next_region[0], overlap_start, next_region[2])
            resolved_regions.append(region)
            extended_regions[i+1] = next_region
        else:

            resolved_regions.append(region)
        i += 1
    final_regions = []
    for region in resolved_regions:
        length = region[2] - region[1] + 1
        if length >= MIN_LENGTH:
            final_regions.append(region)
    return final_regions

def predict_turn(sequence):
    regions = []
    for i in range(len(sequence) - 3):
        segment = sequence[i:i+4]
        Pturn = sum(get_Pturn(residue) for residue in segment) / 4
        Pbend = get_Pbend(*segment)
        if Pturn > TURN_THRESHOLD and Pbend > BEND_THRESHOLD:
            regions.append(('Turn', i+1, i+4))
    return regions

def predict_structure(sequence):
    Helix_beta_regions = predict_Helix_beta(sequence)
    turn_regions = predict_turn(sequence)
    regions = sorted(Helix_beta_regions + turn_regions, key=lambda x: x[1])
    structure = []
    prev_end = 0
    for region in regions:
        structure_type, start, end = region
        if start > prev_end + 1:
            structure.append(('Unknown', prev_end + 1, start - 1))
        structure.append(region)
        prev_end = end
    if prev_end < len(sequence):
        structure.append(('Unknown', prev_end + 1, len(sequence)))
    return structure

def convert_structure(structure):
    structure_Arr = np.zeros(len(sequence))
    for region in structure:
        structure_type, start, end = region
        if structure_type == 'Helix':
            structure_Arr[start-1:end] = 1
        elif structure_type == 'Beta strand':
            structure_Arr[start-1:end] = 2
        elif structure_type == 'Turn':
            structure_Arr[start-1:end] = 3
        elif structure_type == "Unknown":
            structure_Arr[start-1:end] = 4
    
    return structure_Arr
    

def print_structure(structure):
    print("The predicted secondary structure of the sequence is:")
    for region in structure:
        structure_type, start, end = region
        print(f"{structure_type}: {start}-{end}")


def confusion_matrix(structure_arr,ground_truth):
    A_A = 0
    A_B = 0
    A_T = 0
    A_U = 0
    B_A = 0
    B_B = 0
    B_T = 0
    B_U = 0
    T_A = 0
    T_B = 0
    T_T = 0
    T_U = 0
    U_A = 0
    U_B = 0
    U_T = 0
    U_U = 0
    
    for i in range(len(structure_arr)):

        if structure_arr[i] == 1 and ground_truth[i] == 1:      
            A_A += 1
        elif structure_arr[i] == 1 and ground_truth[i] == 2:
            A_B += 1
        elif structure_arr[i] == 1 and ground_truth[i] == 3:
            A_T += 1
        elif structure_arr[i] == 1 and ground_truth[i] == 4:
            A_U += 1
        elif structure_arr[i] == 2 and ground_truth[i] == 1:
            B_A += 1
        elif structure_arr[i] == 2 and ground_truth[i] == 2:
            B_B += 1
        elif structure_arr[i] == 2 and ground_truth[i] == 3:
            B_T += 1
        elif structure_arr[i] == 2 and ground_truth[i] == 4:
            B_U += 1
        elif structure_arr[i] == 3 and ground_truth[i] == 1:
            T_A += 1
        elif structure_arr[i] == 3 and ground_truth[i] == 2:
            T_B += 1
        elif structure_arr[i] == 3 and ground_truth[i] == 3:
            T_T += 1
        elif structure_arr[i] == 3 and ground_truth[i] == 4:
            T_U += 1
        elif structure_arr[i] == 4 and ground_truth[i] == 1:
            U_A += 1
        elif structure_arr[i] == 4 and ground_truth[i] == 2:
            U_B += 1
        elif structure_arr[i] == 4 and ground_truth[i] == 3:
            U_T += 1
        elif structure_arr[i] == 4 and ground_truth[i] == 4:
            U_U += 1
    
    confusion_matrix = np.array([[A_A,A_B,A_T,A_U],[B_A,B_B,B_T,B_U],[T_A,T_B,T_T,T_U],[U_A,U_B,U_T,U_U]])
    
    return confusion_matrix

    

structure = predict_structure(sequence)
structure_arr = convert_structure(structure)
truth_arr = convert_structure(ground_truth)
print_structure(structure)


conf_matrix = confusion_matrix(structure_arr,truth_arr)



The predicted secondary structure of the sequence is:
Unknown: 1-2
Turn: 3-6
Turn: 5-8
Turn: 7-10
Unknown: 11-16
Turn: 17-20
Turn: 21-24
Turn: 22-25
Turn: 23-26
Turn: 27-30
Turn: 29-32
Turn: 30-33
Turn: 32-35
Helix: 35-40
Beta strand: 35-44
Turn: 43-46
Turn: 44-47
Turn: 45-48
Turn: 46-49
Turn: 47-50
Unknown: 51-52
Turn: 53-56
Turn: 55-58
Turn: 56-59
Unknown: 60-84
Turn: 85-88
Turn: 86-89
Turn: 87-90
Turn: 89-92
Unknown: 93-99
Turn: 100-103
Turn: 104-107
Turn: 106-109
Turn: 108-111
Turn: 109-112
Unknown: 113-114
Helix: 115-122
Unknown: 123-140
Turn: 141-144
Turn: 143-146
Turn: 146-149
Turn: 149-152
Helix: 152-157
Turn: 156-159
Turn: 158-161
Unknown: 162-164
Beta strand: 165-170
Turn: 170-173
Unknown: 174-179


In [40]:
print(f"Accuracy: {np.sum(conf_matrix.diagonal())/np.sum(conf_matrix)}")  
print("Confusion Matrix: \n",conf_matrix)

Accuracy: 0.24581005586592178
Confusion Matrix: 
 [[ 7  0  3  2]
 [13  0  0  0]
 [16  6  5 56]
 [16 23  0 32]]
